version: "3.9"

services:
  db:
    image: postgres:17.2
    environment:
      - POSTGRES_DB=zeva
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.4-bookworm
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./next/redis/conf:/usr/local/etc/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    volumes:
      - ./minio:/minio_files
    command: "minio server /minio_files --console-address \":9001\""
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: "curl -I --fail --max-time 10 http://localhost:9000/minio/health/live"
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
  next:
    build: ./next
    command: npm run dev
    volumes:
      - ./next:/next
      - /next/node_modules
    ports:
      - 3000:3000
    env_file:
      - minio.env
    environment:
      - AUTH_SECRET=Ils7nkPcqmp+RHvx2uX8Nwl/MUI8cHnNfmeZS7F8M7k=
      - AUTH_KEYCLOAK_ID=zeva-2-5981
      - AUTH_KEYCLOAK_ISSUER=https://dev.loginproxy.gov.bc.ca/auth/realms/standard
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/zeva?schema=public
      - DATABASE_URL_OLD=postgresql://postgres:postgres@host.docker.internal:5432/zeva?schema=public
      - CHECKPOINT_DISABLE=1
      - CHES_AUTH_URL
      - CHES_EMAIL_URL
      - EMAIL_SERVICE_CLIENT_ID
      - EMAIL_SERVICE_CLIENT_SECRET
      - SENDER_EMAIL
      - SENDER_NAME
      - START_WORKERS=false
      - TZ=America/Vancouver
      - REDIS_TLS_DISABLED=true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --max-time 5 http://localhost:3000/api/health"
      start_period: 15s
      interval: 15s
      timeout: 10s
      retries: 3
  bullmq:
    build: ./next
    command: npm run bullmqDev
    volumes:
      - ./next:/next
      - /next/node_modules
    env_file:
      - minio.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/zeva?schema=public
      - CHECKPOINT_DISABLE=1
      - START_WORKERS=true
      - TZ=America/Vancouver
      - REDIS_TLS_DISABLED=true
    depends_on:
      next:
        condition: service_healthy
