name: Auto Versioning

on:
  pull_request_target:
    types: [labeled, synchronize]
    branches:
      - develop
      - release/*

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # ref: refs/pull/${{ github.event.pull_request.number }}/head

      - name: Verify files changed
        run: |
          pwd
          ls -l
          cd zeva2
          pwd
          ls -l

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "6.0.x"

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true

      # - name: Show ref
      #   run: |
      #     echo ${{ github.event.pull_request.head.ref }}
