name: Auto Versioning

on:
  pull_request_target:
    types: [labeled, synchronize]
    branches:
      - develop
      - release/*

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Verify files changed
        run: |
          pwd
          ls -l
          git status

      - name: Set local branch to PR branch
        run: git checkout -B pr/${{ github.event.pull_request.number }} ${{ github.event.pull_request.head.sha }}
        
      - name: Verify files changed 2
        run: |
          pwd
          ls -l
          git status

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "6.0.x"

      - name: Show GitVersion Config
        run: |
          pwd
          ls -l /opt/hostedtoolcache/GitVersion.Tool
          /opt/hostedtoolcache/GitVersion.Tool/6.0.5/dotnet-gitversion /showconfig

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true

      # - name: Show ref
      #   run: |
      #     echo ${{ github.event.pull_request.head.ref }}
