name: PR Build on Dev

on:
  pull_request_target:
    types: [labeled, synchronize]
    branches:
      - develop
      - release/*

env:
  GIT_URL: https://github.com/bcgov/zeva2.git
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
  DEV_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-dev
  PR_NUMBER: ${{ github.event.pull_request.number }}
  GIT_REF: ${{ github.event.pull_request.head.ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-oc:
    if: >
      (github.event.action == 'labeled' && github.event.label.name == 'build' && ( github.event.pull_request.base.ref == 'develop' || startsWith( github.event.pull_request.base.ref, 'release' ) ) ) ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'build') && ( github.event.pull_request.base.ref == 'develop' || startsWith( github.event.pull_request.base.ref, 'release' ) ) )

    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Set up cache for OpenShift CLI
        id: cache
        uses: actions/cache@v4.2.0
        with:
          path: /usr/local/bin/oc # Path where the `oc` binary will be installed
          key: oc-cli-${{ runner.os }}

      - name: Install OpenShift CLI (if not cached)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
          tar -xvf openshift-client-linux.tar.gz
          sudo mv oc /usr/local/bin/
          oc version --client

      - name: Confirm OpenShift CLI is Available
        run: oc version --client

  versioning:
    if: >
      (github.event.action == 'labeled' && github.event.label.name == 'build' && ( github.event.pull_request.base.ref == 'develop' || startsWith( github.event.pull_request.base.ref, 'release' ) ) ) ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'build') && ( github.event.pull_request.base.ref == 'develop' || startsWith( github.event.pull_request.base.ref, 'release' ) ) )

    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.export-version.outputs.VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "6.0.x"

      - name: Determine Version
        id: version-step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true

      - name: Export Version
        id: export-version
        run: |
          echo "VERSION=${{ steps.version-step.outputs.SemVer }}"
          echo "VERSION=${{ steps.version-step.outputs.SemVer }}" >> $GITHUB_OUTPUT

  verify-pr-author:
    name: Verify PR Author
    needs: [install-oc, versioning]
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR author
        uses: actions/github-script@v6
        with:
          script: |
            const allowedAuthors = ['kuanfandevops', 'emi-hi', 'JulianForeman', 'rogerlcleung', 'tim738745'];
            const prAuthor = context.payload.pull_request.user.login;
            if (!allowedAuthors.includes(prAuthor)) {
              throw new Error(`PR author ${prAuthor} is not allowed.`);
            }
          
  build:
    name: Build Zeva2 Pull Request
    needs: [install-oc, versioning, verify-pr-author]
    uses: ./.github/workflows/build-template.yaml
    with:
      git_ref: refs/pull/${{ github.event.pull_request.number }}/head
      version: ${{ needs.versioning.outputs.VERSION }}
    secrets:
      tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}
