name: Zeva2 Prod CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
  PROD_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-oc:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Set up cache for OpenShift CLI
        id: cache
        uses: actions/cache@v4.2.0
        with:
          path: /usr/local/bin/oc # Path where the `oc` binary will be installed
          key: oc-cli-${{ runner.os }}

      - name: Install OpenShift CLI (if not cached)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
          tar -xvf openshift-client-linux.tar.gz
          sudo mv oc /usr/local/bin/
          oc version --client

      - name: Confirm OpenShift CLI is Available
        run: oc version --client

  versioning:
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.export-version.outputs.VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "6.0.x"

      - name: Determine Version
        id: version-step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true

      - name: Export Version
        id: export-version
        run: |
          echo "VERSION=${{ steps.version-step.outputs.SemVer }}"
          echo "VERSION=${{ steps.version-step.outputs.SemVer }}" >> $GITHUB_OUTPUT

  build:
    name: Build Zeva2 from release branch
    needs: [install-oc, versioning]
    uses: ./.github/workflows/build-template.yaml
    with:
      git_ref: ${{ github.ref_name }}
      version: ${{ needs.versioning.outputs.VERSION }}
    secrets:
      tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}

  tag-images:
    name: Tag Zeva2 images to Prod
    needs: [versioning, build]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1.3
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.TOOLS_NAMESPACE }}

      - name: Tag images to target namespace
        run: |
          oc tag ${{ env.TOOLS_NAMESPACE }}/zeva2-next:${{ needs.versioning.outputs.VERSION}} ${{ env.PROD_NAMESPACE}}/zeva2-next:${{ needs.versioning.outputs.VERSION}}
          oc tag ${{ env.TOOLS_NAMESPACE }}/zeva2-bullmq:${{ needs.versioning.outputs.VERSION}} ${{ env.PROD_NAMESPACE }}/zeva2-bullmq:${{ needs.versioning.outputs.VERSION}}


  approve-prod-deployment:
    name: Approve Prod Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [versioning, tag-images]

    steps:
      - name: Ask for approval for ZEVA2 ${{ needs.versioning.outputs.VERSION  }} Prod deployment
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: emi-hi,tim738745,kuanfandevops,JulianForeman,rogerlcleung
          minimum-approvals: 2
          issue-title: "ZEVA2 ${{ needs.versioning.outputs.VERSION  }} Prod Deployment"

  deploy:
    name: Build Zeva2 from release branch
    needs: [versioning, approve-prod-deployment]
    uses: ./.github/workflows/deploy-template.yaml
    with:
      git_ref: ${{ github.ref_name }}
      version: ${{ needs.versioning.outputs.VERSION }}
      values_file: values-prod.yaml
    secrets:
      manifest-repo-deploy-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}