# This workflow builds and deploys the Zeva2 application to the development environment in OpenShift.
name: Artifactory Test

on:
  push:
    branches:
      - devops/trunk-based-workflow
  workflow_dispatch:

env:
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
  DEV_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # install oc command line tool
  install-oc:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Set up cache for OpenShift CLI
        id: cache
        uses: actions/cache@v4.2.0
        with:
          path: /usr/local/bin/oc # Path where the `oc` binary will be installed
          key: oc-cli-${{ runner.os }}

      - name: Install OpenShift CLI (if not cached)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
          tar -xvf openshift-client-linux.tar.gz
          sudo mv oc /usr/local/bin/
          oc version --client

      - name: Confirm OpenShift CLI is Available
        run: oc version --client
        
  # determine the version of the application
  # A sample version 0.1.0-alpha.91
  # versioning:
  #   runs-on: ubuntu-latest

  #   outputs:
  #     VERSION: ${{ steps.export-version.outputs.VERSION }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Install GitVersion
  #       uses: gittools/actions/gitversion/setup@v3.1.11
  #       with:
  #         versionSpec: "6.0.x"

  #     - name: Determine Version
  #       id: version-step # step id used as reference for output values
  #       uses: gittools/actions/gitversion/execute@v3.1.11
  #       with:
  #         useConfigFile: true

  #     - name: Export Version
  #       id: export-version
  #       run: |
  #         echo "VERSION=${{ steps.version-step.outputs.SemVer }}"
  #         echo "VERSION=${{ steps.version-step.outputs.SemVer }}" >> $GITHUB_OUTPUT

  # build Zeva2 applications on Openshift
  # build:
  #   name: Build Zeva2 from develop
  #   needs: [install-oc, versioning]
  #   uses: ./.github/workflows/build-template.yaml
  #   with:
  #     git_ref: ${{ github.ref_name }}
  #     version: ${{ needs.versioning.outputs.VERSION }}
  #   secrets:
  #     tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
  #     openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
  #     openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}

  # Tag the images from tools namespace to dev namespace
  tag-images:
    name: Tag Zeva2 images to Dev
    # needs: [versioning, build]
    runs-on: ubuntu-latest
    steps:
      - name: Restore oc command from Cache
        uses: actions/cache@v4.2.0
        with:
          path: /usr/local/bin/oc
          key: oc-cli-${{ runner.os }}

      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1.3
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.TOOLS_NAMESPACE }}

      - name: Tag images to target namespace
        run: |

          oc tag ${{ env.TOOLS_NAMESPACE }}/zeva2-next:0.4.0-devops-trunk-based-workflow.1 ${{ env.DEV_NAMESPACE}}/zeva2-next:0.4.0-devops-trunk-based-workflow.1
          oc tag ${{ env.TOOLS_NAMESPACE }}/zeva2-bullmq:0.4.0-devops-trunk-based-workflow.1 ${{ env.DEV_NAMESPACE }}/zeva2-bullmq:0.4.0-devops-trunk-based-workflow.1

      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Tag images to Artifactory
        env:
          ARTIFACTORY_REGISTRY: ${{ secrets.ARTIFACTORY_REGISTRY }}
          ARTIFACTORY_REPO: ${{ secrets.ARTIFACTORY_REPO }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          set -euo pipefail
          VERSION="0.4.0-devops-trunk-based-workflow.1"
          OPENSHIFT_REGISTRY="$(oc registry info --public)"
          oc registry login --registry="${OPENSHIFT_REGISTRY}" --to=/tmp/openshift-auth.json
          skopeo login --authfile /tmp/artifactory-auth.json \
            --username "${ARTIFACTORY_USERNAME}" \
            --password "${ARTIFACTORY_PASSWORD}" \
            "${ARTIFACTORY_REGISTRY}"
          echo "both openshift abd artifactory login successful"
          skopeo copy --src-tls-verify=false --dest-tls-verify=true \
            --src-authfile /tmp/openshift-auth.json --dest-authfile /tmp/artifactory-auth.json \
            "docker://${OPENSHIFT_REGISTRY}/${{ env.TOOLS_NAMESPACE }}/zeva2-next:${VERSION}" \
            "docker://${ARTIFACTORY_REGISTRY}/${ARTIFACTORY_REPO}/zeva2/dev/zeva2-next:${VERSION}"

          # skopeo copy --src-tls-verify=false --dest-tls-verify=true \
          #   --src-authfile /tmp/openshift-auth.json --dest-authfile /tmp/artifactory-auth.json \
          #   "docker://${OPENSHIFT_REGISTRY}/${{ env.TOOLS_NAMESPACE }}/zeva2-bullmq:${VERSION}" \
          #   "docker://${ARTIFACTORY_REGISTRY}/${ARTIFACTORY_REPO}/zeva2/dev/zeva2-bullmq:${VERSION}"

  # deploy to Dev
  deploy:
    name: Deploy Zeva2 test artifact TO Dev
    needs: [install-oc,tag-images]
    uses: ./.github/workflows/deploy-template.yaml
    with:
      git_ref: ${{ github.ref_name }}
      version: ${{ needs.versioning.outputs.VERSION }}
      values_file: values-dev.yaml
    secrets:
      manifest-repo-deploy-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
